<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "registeraddress"
 *
 * Auto generated by Extension Builder 2013-08-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'registerttaddress',
	'description' => 'Simple Registration for tt_address',
	'category' => 'plugin',
	'author' => 'Sascha Löffler',
	'author_email' => 'sl@afm-koeln.de',
	'author_company' => 'Atelier für Mediengestaltung',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>