<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "registeraddress"
 *
 * Auto generated by Extension Builder 2013-08-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Register to tt_address',
	'description' => 'Simple Registration for tt_address for newsletter registration',
	'category' => 'plugin',
	'author' => 'Sascha Löffler',
	'author_email' => 'lsascha@gmail.com',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.12',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-8.7.99',
			'tt_address' => '3.1.0-3.3.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
